# Generated by Django 4.1.7 on 2023-03-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_plant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
