# Generated by Django 4.1.7 on 2023-03-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='p_year',
            new_name='s_name',
        ),
    ]
