# Generated by Django 4.1.7 on 2023-03-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_movie_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
